export enum ApiErrorCodeEnum {
  // Healthcheck
  HEALTHCHECK = 'HEALTHCHECK',

  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',

  AUTH_EXPIRED_RESET_TOKEN = 'AUTH_EXPIRED_RESET_TOKEN',

  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',

  AUTH_INVALID_RESET_TOKEN = 'AUTH_INVALID_RESET_TOKEN',

  AUTH_EXPIRED_ACCESS_TOKEN = 'AUTH_EXPIRED_ACCESS_TOKEN',
}
