version: '3.8'

services:
  db:
    image: postgres:17
    restart: unless-stopped
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [ 'CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - ${API_PORT}:${API_PORT}
      - '${PRISMA_STUDIO_PORT:-5555}:5555'
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?schema=public
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
    volumes:
      - .:/app
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
      - ./docker/redis/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./docker/redis/redis.conf.template:/usr/local/etc/redis/redis.conf.template
    entrypoint: [ "sh", "/usr/local/bin/entrypoint.sh" ]
volumes:
  postgres_data:
  redis_data:
